title: Ruth Neville
description: Academic website of Ruth Neville
theme: jekyll-theme-minimal

# Optional
author: Ruth Neville
email: ruth.neville@ucl.ac.uk
logo: /assets/img/photo.jpg
show_downloads: false
google_analytics: # add tracking ID if you have one
