title: Ruth Neville
description: Academic website of Ruth Neville
theme: jekyll-theme-minimal
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Optional
author: Ruth Neville
email: ruth.neville@ucl.ac.uk
logo: /assets/img/photo.jpg
show_downloads: false
google_analytics: # add tracking ID if you have one
