defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: home


title: "Ruth Neville"
tagline: "Data scientist & geographer — international student mobility, forecasting, GIS"
url: "" # set to your custom domain without trailing slash, e.g. https://ruthneville.uk
baseurl: "" # leave empty for user/organisation site
author:
  name: "Ruth Neville"
  email: "you@university.ac.uk"
  orcid: ""
  scholar: ""
  github: "ruthneville" # change to your handle
  twitter: ""
  bluesky: ""
  linkedin: ""

theme: null
markdown: kramdown
kramdown:
  input: GFM
permalink: /:categories/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections (optional future blog)
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Navigation
nav:
  - title: Home
    url: /
  - title: About
    url: /pages/about/
  - title: Research
    url: /pages/research/
  - title: Publications
    url: /pages/publications/
  - title: Teaching
    url: /pages/teaching/
  - title: Talks & Media
    url: /pages/talks/
  - title: Contact
    url: /pages/contact/

# Appearance
brand_color: "#0ea5e9"
accent_color: "#7c3aed"
light_bg: "#f8fafc"
dark_bg: "#0b1020"
