title: Ruth Neville
description: Academic website of Ruth Neville
remote_theme: pages-themes/tactile@v0.2.0

plugins:
  - jekyll-remote-theme

# Optional
author: Ruth Neville
email: your.email@example.com
logo: /assets/img/photo.jpg
show_downloads: false
google_analytics: # UA-XXXXXXXXX-X
