title: "Ruth Neville"
description: "Spatial Data Scientist | Migration & Mobility | Forecasting"
baseurl: "" # leave empty if using your root domain
url: "https://ruthneville.github.io" # change to your GitHub Pages URL

remote_theme: "mmistakes/minimal-mistakes@4.27.1"

plugins:
  - jekyll-include-cache

# Author details
author:
  name: "Ruth Neville"
#  avatar: "/assets/images/photo.jpg"
  bio:  "Spatial Data Scientist | Migration & Mobility | Computational Social Science"
  location: "London, UK"
  email: "ruth.neville@ucl.ac.uk"

# Optional navigation (edit as needed)
nav:
  - title: "About"
    url: /about/
  - title: "Publications"
    url: /publications/
  - title: "CV"
    url: /cv/

# Google Analytics etc. can be added later
