title: Ruth Neville
description: Academic website of Ruth Neville
theme: jekyll-theme-minimal

# Optional
author: Ruth Smith
email: your.email@example.com
logo: /assets/img/photo.jpg
show_downloads: false
google_analytics: # add tracking ID if you have one
